// The avatar module shared with the classic page (src/isharati/app/static), imported through the @static alias.
declare module "@static/avatar.js" {
  export class SignAvatar {
    constructor(canvas: HTMLCanvasElement);
    load(url: string): Promise<SignAvatar>;
    resize(): void;
    setFrames(frames: { fps: number; frames: number[][][]; blend?: (number | null)[][]; blend_names?: string[] } | null): void;
    render(t: number, dt?: number): void;
    probe(): Record<string, unknown>;
    renderer: { dispose(): void; setClearColor(color: number, alpha: number): void };
    vrm: unknown;
  }
}
declare module "@static/outfits.js" {
  export const PRESETS: Record<"original" | "hijab" | "shemagh", Record<string, unknown>>;
  export function applyOutfit(avatar: unknown, outfit: Record<string, unknown>): void;
}
declare module "@static/stats.json" {
  const stats: any;  // generated by scripts/eval/app_stats.py; typed as Stats where it is used
  export default stats;
}
